services:
  server:
    build: .
    container_name: server
    ports:
      - 80:80
    depends_on:
      - db
    volumes:
      - ./public:/server/public
      - ./views:/server/views
      - ./models:/server/models
      - ./routes:/server/routes
      - ./controllers:/server/controllers

  db:
    image: mongo:6.0.5
    container_name: db
    volumes:
      - ./data:/data/db
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=root
      - MONGODB_INITDB_ROOT_PASSWORD=password