services:
  server:
    build: .
    container_name: server
    restart: always
    ports:
      - 80:3000
    depends_on:
      - db
    volumes:
      - ./public:/server/public
      - ./views:/server/views
      - ./models:/server/models
      - ./routes:/server/routes
      - ./controllers:/server/controllers
      - ./data:/server/data

  db:
    image: mongo:6.0.5
    container_name: db
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=root
      - MONGODB_INITDB_ROOT_PASSWORD=password