services:
  server:
    build: .
    container_name: server
    ports:
      - 80:3000
    depends_on:
      - db
    volumes:
      - ./public:/server/public
      - ./icons:/server/icons
      - ./styles:/server/styles
      - ./views:/server/views

  db:
    image: mongo:6.0.5
    container_name: db
    volumes:
      - ./data:/data/db
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=root
      - MONGODB_INITDB_ROOT_PASSWORD=password